version: '2'
services:
    web:
        build: .
        ports:
        - "4000:4000"
        volumes:
        - .:/var/www/blog/
        links:
        - "db:db"
        environment:
            MIX_ENV: "dev"

    db:
        image: "postgres:9.4"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: lilarcor1
        volumes_from:
            - dbdata

    # for persistance of database data
    dbdata:
        image: "postgres:9.4"
        volumes:
            - /var/lib/postgres
        command: "true"
